# Source: mariadb-operator/templates/webhook-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-operator-webhook-cert
  labels:
    
    helm.sh/chart: mariadb-operator-0.30.0
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: mariadb-operator
    
    app.kubernetes.io/version: "v0.0.30"
    
    app.kubernetes.io/managed-by: Helm
spec:
  commonName: mariadb-operator-webhook.mariadb-operator.svc
  dnsNames:
    - mariadb-operator-webhook.mariadb-operator.svc.cluster.local
    - mariadb-operator-webhook.mariadb-operator.svc
    - mariadb-operator-webhook.mariadb-operator
    - mariadb-operator-webhook
  issuerRef:
    kind: Issuer
    name: mariadb-operator-selfsigned-issuer
  revisionHistoryLimit: 3
  secretName: mariadb-operator-webhook-cert
