# Source: mariadb-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
  labels:
    
    helm.sh/chart: mariadb-operator-0.19.0
    app.kubernetes.io/name: mariadb-operator
    app.kubernetes.io/instance: mariadb-operator
    app.kubernetes.io/version: "v0.0.19"
    app.kubernetes.io/managed-by: Helm
spec:
  
  replicas: 3
  
  selector:
    matchLabels:
      
      app.kubernetes.io/name: mariadb-operator
      app.kubernetes.io/instance: mariadb-operator
  template:
    metadata:
      
      labels:
        
        app.kubernetes.io/name: mariadb-operator
        app.kubernetes.io/instance: mariadb-operator
    spec:
      serviceAccountName: mariadb-operator
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 10
      
      
      
      
      containers:
        - image: "docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.19"
          imagePullPolicy: IfNotPresent
          name: controller
          args:
            - --metrics-addr=:8080
            - --log-level=INFO
            - --leader-elect
            - --service-monitor-reconciler
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          env: 
            - name: CLUSTER_NAME
              value: cluster.local
            - name: MARIADB_OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MARIADB_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MARIADB_OPERATOR_SA_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
