# Source: mariadb-operator/templates/webhook-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mariadb-operator-selfsigned-issuer
  labels:
    
    helm.sh/chart: mariadb-operator-0.30.0
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: mariadb-operator
    
    app.kubernetes.io/version: "v0.0.30"
    
    app.kubernetes.io/managed-by: Helm
spec:
  selfSigned: {}
