# Source: mariadb-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-operator
subjects:
- kind: ServiceAccount
  name: mariadb-operator
  namespace: dev
