# Source: mariadb-operator/templates/webhook-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-operator-webhook
  labels:
    helm.sh/chart: mariadb-operator-0.19.0
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: mariadb-operator
    
    app.kubernetes.io/version: "v0.0.19"
    
    app.kubernetes.io/managed-by: Helm
