# Source: mariadb-operator/templates/webhook-config.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: mariadb-operator-webhook
  labels:
    
    helm.sh/chart: mariadb-operator-0.19.0
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: mariadb-operator
    
    app.kubernetes.io/version: "v0.0.19"
    
    app.kubernetes.io/managed-by: Helm
  annotations:
    
    
    
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-backup
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vbackup.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backups
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-connection
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vconnection.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - connections
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-database
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vdatabase.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - databases
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-grant
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vgrant.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - grants
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-mariadb
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vmariadb.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - mariadbs
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-restore
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vrestore.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - restores
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-sqljob
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vsqljob.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - sqljobs
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: mariadb-operator-webhook
        namespace: dev
        path: /validate-mariadb-mmontes-io-v1alpha1-user
      
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lSQU9Gb2NRdVM0MmpYQjlLOVpvMjc3dkV3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWJXRnlhV0ZrWWkxdmNHVnlZWFJ2Y2pBZUZ3MHlOREE1TWpReU1USTBNREJhRncweQpOVEE1TWpReU1USTBNREJhTUJzeEdUQVhCZ05WQkFNVEVHMWhjbWxoWkdJdGIzQmxjbUYwYjNJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETVU0RWlPTVBzQkorTFo5ZWJkU2xNcytNVS8yTWUKY1UrUUJKdEV1elUzRlgwbGRsTHQ2bStTaEVSVTZiOUR2dnNjdmFncG9RU25pRTZVZWhGa21PK0NWRmdxZ0doZQoyVktLRUpya0RDUml1S1AweFVUOXJxOGFZUmlUcWJFTEtaTFh4WWNLOGx0dE12OTk5eDBhUDArNEhqWnB0S2psCjNNeTJqVjFqRXg5ZCtONnpvMGF3VHVaTVEraFAzN2d6Q1EvUmFVT2pzUVpBNjZOb3VlUW5KVDVCY04zZ00wRlEKU2RJUzdUMnpERkxteHhVaVlnRnpKNDY2WFZCOHJ2VzFGN2J2M3hoZjFjejk4S1dPRmdBSVBRZFhwZGY5UTRLNwpVcFQ3R0tubWI5cjdXWFNCaHh2b2VVd09MUDNOcmNqTFJQQzZVTlpYTjBwOFBBNEhvRGJjM1pSMUFnTUJBQUdqCllUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBxa2FnVjFPVms2ejk4Wmowa3c5ZHlpSgpQanN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE1NlM3MkJuOFB6cEE0TzBKMFc4dHdZL0w0Nm15TEJoUmlrClIvNVNsQ01NK29PSHViK3B2MXM3TUdHL1VUK0NQNDVjTDI4TnczRkRDY1VWN1lsbXNYSTh2TGZGZ0xDVHBibHQKQ1lhdzQzYjdhb3NzbEVBQzE3RERZUmRjRnN2V2NoSlpiWStQeUVMbmhVNXcvZi9CUWtqYWQxbE9PNHVXcXFXWApYaFI4Q1pGQXdlNkNjdWhuOHpucmp0cFR2SmN4WjV5UnlwMU44M3ZYMU0zSUpML1hLQ2M5TTVreFZ5bWg3RGVICjBpWnc0NDFoeUhyMW52OXp1bnZvcEpyTlpUMzJZekNRRVZPSDY3Sy9mMHY2QUMxNGs3QnhjYzA1a3c4dy90OFAKSHo3L3hUaWtkU3g3SzNmOENKQkNFNDJtMFdiSjB5dzFSa3c4dndjTUtGdGVEVFNLMElNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      
    failurePolicy: Fail
    name: vuser.kb.io
    rules:
      - apiGroups:
          - mariadb.mmontes.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - users
    sideEffects: None
