apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ns.yaml
- resources/certificate-mariadb-operator-webhook-cert.yaml
- resources/clusterrole-mariadb-operator-edit.yaml
- resources/clusterrole-mariadb-operator-view.yaml
- resources/clusterrole-mariadb-operator.yaml
- resources/clusterrolebinding-mariadb-operator.yaml
- resources/clusterrolebinding-mariadb-operator:auth-delegator.yaml
- resources/configmap-mariadb-operator-env.yaml
- resources/deployment-mariadb-operator-webhook.yaml
- resources/deployment-mariadb-operator.yaml
- resources/issuer-mariadb-operator-selfsigned-issuer.yaml
- resources/mutatingwebhookconfiguration-mariadb-operator-webhook.yaml
- resources/role-mariadb-operator.yaml
- resources/rolebinding-mariadb-operator.yaml
- resources/service-mariadb-operator-metrics.yaml
- resources/service-mariadb-operator-webhook-metrics.yaml
- resources/service-mariadb-operator-webhook.yaml
- resources/serviceaccount-mariadb-operator-webhook.yaml
- resources/serviceaccount-mariadb-operator.yaml
- resources/servicemonitor-mariadb-operator-webhook.yaml
- resources/servicemonitor-mariadb-operator.yaml
- resources/validatingwebhookconfiguration-mariadb-operator-webhook.yaml
- resources/secret-mariadb-operator-webhook-default-cert.yaml
