# Replica Cluster manifest ───────────────────────────────────────
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: butler3-replica                    # <— new cluster name
  namespace: cnpg-butler3-replica
spec:
  # ---- PostgreSQL image (new major) ----
  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:14.5
  instances: 1                        # number of pods
  storage:
    size: 4000Gi

  # ---------- BOOTSTRAP FROM SOURCE ----------
  bootstrap:
    pg_basebackup:                    # “clone” via pg_basebackup + stream
      source: butler3-primary         # must match externalClusters[].name

  replica:
    enabled: true
    source: butler3-primary

  # ---------- CONNECTION DETAILS FOR SOURCE ----------
  externalClusters:
  - name: butler3-primary             # logical name referenced above
    connectionParameters:
      host: usdf-butler3-db-svc.slac.stanford.edu    # Service pointing to primary
      user: streaming_replica                        # role with REPLICATION privilege
      sslmode: verify-full
    sslKey:
      name: butler3-primary-replication
      key: tls.key
    sslCert:
      name: butler3-primary-replication
      key: tls.crt
    sslRootCert:
      name: butler3-primary-ca
      key: ca.crt

  # ---- (Optional) post-bootstrap SQL or parameters --------------
  postgresql:
    parameters:
      checkpoint_timeout: "3600"
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: 250ms
      idle_in_transaction_session_timeout: "14400000"
      log_statement: none
      log_temp_files: "1"
      maintenance_work_mem: 2GB
      max_connections: "3000"
      max_wal_size: 256GB
      min_wal_size: 64GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      random_page_cost: "1.1"
      shared_buffers: 16GB
      work_mem: 160MB
      statement_timeout: "14400000"
      wal_keep_size: 64GB

  resources:
    requests:
      memory: 64Gi
      cpu: 8
    limits:
      memory: 128Gi
      cpu: 16

  monitoring:
    enablePodMonitor: true
