
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler3
  namespace: prod2
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-butler3
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 8

  imageName:  ghcr.io/lsst-sqre/cnpg-postgres-images:14.5
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      checkpoint_timeout: "3600"
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: 250ms
      idle_in_transaction_session_timeout: "14400000"
      log_statement: none
      log_statement: all
      log_temp_files: "1"
      maintenance_work_mem: 2GB
      max_connections: "3000"
      max_wal_size: 256GB
      min_wal_size: 64GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      random_page_cost: "1.1"
      shared_buffers: 16GB
      work_mem: 160MB
      statement_timeout: "14400000"
      wal_keep_size: 64GB

  resources:
    requests:
      memory: 128Gi
      cpu: 16
    limits:
      memory: 256Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 20000Gi
