
resources:
- ns.yaml
- cnpg-butler3-database.yaml
- cnpg-butler3-pooler.yaml
- backup.yaml
- cnpg-butler3-pooler-service.yaml
- cnpg-butler3-db-svc.yaml

secretGenerator:
- name: usdf-butler-butler-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret

namespace: prod2
