---
apiVersion: v1
kind: Service
metadata:
  name: metallb-vlan832-2
  annotations:
    # a valid address-pool is required by policy
    metallb.io/address-pool: sdf-ad-ingest
    # prefer flexiable ip (leave this empty), uncomment below for mandatory fixed IP, please check SCS if the ip is free  
    # metallb.io/loadBalancerIPs: xxx
spec:
  ports:
  - name: pgbouncer
    port: 3306
    targetPort: 3306
  selector:
    app: metallb-vlan832-2
  # for in-cluster traffic, preferred
  type: ClusterIP
  # for cross vCluster traffic, uncomment below
  # type: Loadbalancer
  # avoid Nodeports, required by policy
  allocateLoadBalancerNodePorts: false
  loadBalancerSourceRanges:
  - 134.79.0.0/16
  - 172.16.0.0/8
