---
apiVersion: v1
kind: Service
metadata:
  name: service-name
  annotations:
    metallb.io/address-pool: sdf-services
spec:
  ports:
  - name: pgbouncer
    port: 3306
    targetPort: 3306
  selector:
    app: app-name
  # for in-vCluster traffic
  type: ClusterIP
